Repository atlanhq/atlan-java, pull requests merged in 2024-06, with the labels that each got.

#706 Fix glossaries test and icon for experimental features
  .github/release.yml
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportGlossariesTest.kt
Labels: ignore

#707 Improve testing interfaces
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  package-toolkit/testing/src/main/resources/log4j2.xml
  samples/packages/admin-export/src/test/kotlin/ExportAllAdminInfoTest.kt
  samples/packages/admin-export/src/test/kotlin/ExportAllPoliciesTest.kt
  samples/packages/admin-export/src/test/kotlin/ExportUsersTest.kt
  samples/packages/adoption-export/src/test/kotlin/ExportChangesTest.kt
  samples/packages/adoption-export/src/test/kotlin/ExportRawViewsTest.kt
  samples/packages/adoption-export/src/test/kotlin/ExportUniqueUserViewsTest.kt
  samples/packages/asset-export-basic/src/test/kotlin/ExportAllAssetsTest.kt
  samples/packages/asset-export-basic/src/test/kotlin/NoGlossariesTest.kt
  samples/packages/asset-export-basic/src/test/kotlin/OnlyGlossariesTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportDataDomainTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportGlossariesTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportSourceTagValuesTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/InvalidUsersGroupsTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/LinkTermsTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/SameNameCategoriesTest.kt
  samples/packages/cube-assets-builder/src/test/kotlin/com/atlan/pkg/cab/AssetRemoverTest.kt
  samples/packages/cube-assets-builder/src/test/kotlin/com/atlan/pkg/cab/CreateThenUpsertCABTest.kt
  samples/packages/duplicate-detector/src/test/kotlin/DuplicateDetectorTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorArchivedTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorMultipleTargetTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorPatternTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorSingleTargetTest.kt
  samples/packages/lineage-builder/src/test/kotlin/PartialAssetsTest.kt
  samples/packages/metadata-impact-report/src/test/kotlin/ImpactReportTest.kt
  samples/packages/openapi-spec-loader/src/test/kotlin/ImportPetStoreTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/AssetRemoverTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpsertRABTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/InvalidParentTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/PartialAssetsTest.kt
Labels: ignore

#716 Add methods to write arbitrary data to CSV
  integration-tests/src/test/java/com/atlan/java/sdk/CubeTest.java
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVWriter.kt
  samples/packages/cube-assets-builder/src/test/kotlin/com/atlan/pkg/cab/CreateThenUpsertCABTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpsertRABTest.kt
  samples/packages/relational-assets-builder/src/test/resources/assets.csv
  samples/packages/relational-assets-builder/src/test/resources/assets_latest.csv
  samples/packages/relational-assets-builder/src/test/resources/assets_partial.csv
  samples/packages/relational-assets-builder/src/test/resources/invalid_parent.csv
Labels: packages

#719 Trim whitespace from key CSV inputs
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/RowDeserializer.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/CategoryImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/DomainImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/TermImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/AssetImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/AssetImporter.kt
Labels: bug

#718 Segregate log files for integration tests
  .github/workflows/test.yml
  .gitignore
  integration-tests/src/test/java/com/atlan/java/sdk/AtlanLiveTest.java
  integration-tests/src/test/resources/log4j2.xml
Labels: ignore

#709 CXD-40 Map Lake Formation Tags to Custom Metadata on Assets
  .github/workflows/merge.yml
  .github/workflows/release.yml
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/lake-formation-tag-sync/build.gradle.kts
  samples/packages/lake-formation-tag-sync/src/main/kotlin/LakeFormationTagSyncCfg.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/CSVProducer.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/EnumCreator.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/LakeTagSynchronizer.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/TagToMetadataMapper.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/model/ColumnLFTag.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/model/LFTable.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/model/LFTableInfo.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/model/LFTagData.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/model/LFTagPair.kt
  samples/packages/lake-formation-tag-sync/src/main/resources/package.pkl
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/CSVProducerTest.kt
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/EnumCreatorTest.kt
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/LakeTagSynchronizerTest.kt
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/SerdeTest.kt
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/TagToMetadataMapperTest.kt
  samples/packages/lake-formation-tag-sync/src/test/resources/lftag_association_1.json
  settings.gradle.kts
Labels: packages

#721 Abstracts OpenLineage for Spark-based representation
  sdk/src/main/java/com/atlan/model/lineage/OpenLineageDataset.java
  sdk/src/main/java/com/atlan/model/lineage/OpenLineageEvent.java
  sdk/src/main/java/com/atlan/model/lineage/OpenLineageInputDataset.java
  sdk/src/main/java/com/atlan/model/lineage/OpenLineageJob.java
  sdk/src/main/java/com/atlan/model/lineage/OpenLineageOutputDataset.java
  sdk/src/main/java/com/atlan/model/lineage/OpenLineageRun.java
Labels: experimental

#722 Adds custom package to cleanup tests
  samples/packages/tests-cleanup/build.gradle.kts
  samples/packages/tests-cleanup/src/main/kotlin/TestsCleanup.kt
  samples/packages/tests-cleanup/src/main/kotlin/TestsCleanupCfg.kt
  samples/packages/tests-cleanup/src/main/resources/package.pkl
  settings.gradle.kts
Labels: enhancement

#723 Adds further objects to test cleanup
  .github/workflows/merge.yml
  .github/workflows/release.yml
  samples/packages/tests-cleanup/src/main/kotlin/TestsCleanup.kt
  samples/packages/tests-cleanup/src/main/resources/package.pkl
Labels: ignore

#724 Bump to latest Docker actions
  .github/workflows/custom-package-container.yml
  .github/workflows/merge.yml
  .github/workflows/release.yml
  samples/packages/tests-cleanup/src/main/kotlin/TestsCleanup.kt
Labels: ignore
