Repository atlanhq/atlan-java, pull requests merged in 2024-11, with the labels that each got.

#987 Bump to latest dependencies
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com.atlan.kotlin-custom-package.gradle.kts
  gradle/libs.versions.toml
  package-toolkit/config/build.gradle.kts
  package-toolkit/config/src/main/resources/PklProject
  package-toolkit/config/src/main/templates/BuildInfo.pkl
  package-toolkit/runtime/build.gradle.kts
  package-toolkit/runtime/src/main/resources/csa-connectors-objectstore.pkl
  samples/packages/admin-export/src/main/resources/package.pkl
  samples/packages/adoption-export/src/main/resources/package.pkl
  samples/packages/api-token-connection-admin/src/main/resources/package.pkl
  samples/packages/asset-export-basic/src/main/resources/package.pkl
  samples/packages/asset-import/src/main/resources/package.pkl
  samples/packages/cube-assets-builder/src/main/resources/package.pkl
  samples/packages/custom-metadata-extender/src/main/resources/package.pkl
  samples/packages/duplicate-detector/src/main/resources/package.pkl
  samples/packages/enrichment-migrator/src/main/resources/package.pkl
  samples/packages/lake-formation-tag-sync/src/main/resources/package.pkl
  samples/packages/lineage-builder/src/main/resources/package.pkl
  samples/packages/metadata-impact-report/src/main/resources/package.pkl
  samples/packages/openapi-spec-loader/src/main/resources/package.pkl
  samples/packages/owner-propagator/src/main/resources/package.pkl
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  samples/packages/relational-assets-builder/src/main/resources/package.pkl
  samples/packages/tests-cleanup/src/main/resources/package.pkl
  samples/pipelines/asset-scorer/src/main/resources/package.pkl
  samples/pipelines/verification-enforcer/src/main/resources/package.pkl
  samples/typedefs/build.gradle.kts
  typedef-toolkit/model/build.gradle.kts
  typedef-toolkit/model/src/main/resources/PklProject
  typedef-toolkit/model/src/main/resources/PklProject.deps.json
  typedef-toolkit/model/src/main/templates/BuildInfo.pkl
Labels: dependencies

#988 Extend off-heap caching to all custom package asset caches
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/AssetCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/CategoryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/ConnectionCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataDomainCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataProductCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/GlossaryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/LinkCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/TermCache.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/DomainImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/GTCImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/ConnectionImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ConnectionImporter.kt
  sdk/src/main/java/com/atlan/cache/AbstractOffHeapCache.java
Labels: enhancement, packages

#989 Adds necessary CLI args for JVM for off-heap caches
  containers/base/Dockerfile
Labels: ignore

#991 Adds necessary CLI args for JVM for off-heap caches
  containers/base/Dockerfile
Labels: ignore

#993 Move base image to JDK to include needed prereqs for off-heap caching library
  containers/base/Dockerfile
Labels: ignore

#994 Pass through failOnErrors to allow continuation beyond failures
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/AssetImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ColumnImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ConnectionImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/DatabaseImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/MaterializedViewImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/SchemaImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/TableImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ViewImporter.kt
Labels: bug

#995 Fix off-heap caching (and link caching in particular)
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/CategoryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/ConnectionCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataDomainCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataProductCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/GlossaryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/LinkCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/TermCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/AssetRefXformer.kt
Labels: ignore

#996 Fix off-heap caching initialization (with no existing assets)
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/AssetCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/CategoryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/ConnectionCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataDomainCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataProductCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/GlossaryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/LinkCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/TermCache.kt
Labels: ignore

#998 Further off-heap caching fixes
  containers/base/Dockerfile
  gradle.properties
  gradle/libs.versions.toml
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/AssetCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/CategoryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/ConnectionCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataDomainCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataProductCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/GlossaryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/LinkCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/TermCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVReader.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/ImportResults.kt
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/CategoryImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/DomainImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/TermImporter.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportGlossariesTest.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/FieldImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/Importer.kt
  samples/packages/lake-formation-tag-sync/src/main/kotlin/com/atlan/pkg/lftag/LakeTagSynchronizer.kt
  samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/Loader.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  sdk/src/main/java/com/atlan/AtlanClient.java
  sdk/src/main/java/com/atlan/cache/AbstractMassCache.java
  sdk/src/main/java/com/atlan/cache/AbstractOffHeapCache.java
  sdk/src/main/java/com/atlan/cache/AtlanTagCache.java
  sdk/src/main/java/com/atlan/cache/CustomMetadataCache.java
  sdk/src/main/java/com/atlan/cache/GroupCache.java
  sdk/src/main/java/com/atlan/cache/OffHeapAssetCache.java
  sdk/src/main/java/com/atlan/cache/RoleCache.java
  sdk/src/main/java/com/atlan/cache/UserCache.java
  sdk/src/main/java/com/atlan/exception/ErrorCode.java
  sdk/src/main/java/com/atlan/util/AssetBatch.java
  sdk/src/main/java/com/atlan/util/ParallelBatch.java
Labels: ignore

#1006 Parse precision, scale, max length and raw definition from dataType
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/RowDeserializer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ColumnImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpsertRABTest.kt
  sdk/src/main/java/com/atlan/util/AssetBatch.java
Labels: enhancement

#1005 CXD-270: Added new connector types
  sdk/src/main/java/com/atlan/model/enums/AtlanConnectorType.java
Labels: enhancement

#1009 Fix initialization of import results details
  integration-tests/src/test/java/com/atlan/java/sdk/ModelTest.java
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVReader.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/ImportResults.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/Importer.kt
  sdk/src/main/java/com/atlan/cache/AbstractOffHeapCache.java
Labels: ignore

#1010 Reworked tests to match latest tenant setups
  gradle/libs.versions.toml
  integration-tests/src/test/java/com/atlan/java/sdk/PurposeTest.java
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/AssetCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/CategoryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/ConnectionCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataDomainCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataProductCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/GlossaryCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/LinkCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/TermCache.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportDataDomainTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportGlossariesTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportSourceTagValuesTest.kt
  samples/packages/asset-import/src/test/resources/data_domain.csv
  samples/packages/asset-import/src/test/resources/glossary.csv
  sdk/src/main/java/com/atlan/cache/AbstractMassCache.java
  sdk/src/main/java/com/atlan/cache/AtlanTagCache.java
  sdk/src/main/java/com/atlan/cache/CustomMetadataCache.java
  sdk/src/main/java/com/atlan/cache/GroupCache.java
  sdk/src/main/java/com/atlan/cache/RoleCache.java
  sdk/src/main/java/com/atlan/cache/UserCache.java
Labels: ignore

#1013 DVX-715 Change AZURE_STORAGE_CONTAINER_NAME to objectstore
  package-toolkit/config/src/main/resources/Renderers.pkl
Labels: bug

#1015 Concurrency fixes for tests and off-heap caching
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVReader.kt
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/admin-export/src/test/kotlin/ExportAllAdminInfoTest.kt
  samples/packages/admin-export/src/test/kotlin/ExportAllPoliciesTest.kt
  samples/packages/admin-export/src/test/kotlin/ExportUsersTest.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/AssetChanges.kt
  samples/packages/adoption-export/src/test/kotlin/ExportChangesTest.kt
  samples/packages/adoption-export/src/test/kotlin/ExportDetailsTest.kt
  samples/packages/adoption-export/src/test/kotlin/ExportRawViewsTest.kt
  samples/packages/adoption-export/src/test/kotlin/ExportUniqueUserViewsTest.kt
  samples/packages/asset-export-basic/src/test/kotlin/ExportAllAssetsTest.kt
  samples/packages/asset-export-basic/src/test/kotlin/NoGlossariesTest.kt
  samples/packages/asset-export-basic/src/test/kotlin/OnlyGlossariesTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportDataDomainTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportGlossariesTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportSourceTagValuesTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/InvalidUsersGroupsTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/LinkTermsTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/SameNameCategoriesTest.kt
  samples/packages/cube-assets-builder/src/test/kotlin/com/atlan/pkg/cab/AssetRemoverTest.kt
  samples/packages/cube-assets-builder/src/test/kotlin/com/atlan/pkg/cab/CreateThenUpsertCABTest.kt
  samples/packages/duplicate-detector/src/test/kotlin/DuplicateDetectorTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorArchivedTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorMultipleTargetTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorPatternTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorSingleTargetTest.kt
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/CSVProducerTest.kt
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/EnumCreatorTest.kt
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/LakeTagSynchronizerTest.kt
  samples/packages/lake-formation-tag-sync/src/test/kotlin/com/atlan/pkg/lftag/SerdeTest.kt
  samples/packages/lineage-builder/src/test/kotlin/PartialAssetsTest.kt
  samples/packages/metadata-impact-report/src/test/kotlin/ImpactReportTest.kt
  samples/packages/openapi-spec-loader/src/test/kotlin/ImportFileTest.kt
  samples/packages/openapi-spec-loader/src/test/kotlin/ImportURLTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/AssetRemoverTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpsertRABTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/InvalidParentTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/PartialAssetsTest.kt
  sdk/src/main/java/com/atlan/cache/AbstractOffHeapCache.java
  sdk/src/main/java/com/atlan/cache/OffHeapAssetCache.java
  sdk/src/main/java/com/atlan/util/ParallelBatch.java
Labels: ignore

#1016 Attempt to resolve OOM in GitHub Action
  .github/workflows/merge.yml
Labels: ignore

#1018 Updated integration test to align to new tenant setup
  gradle/libs.versions.toml
  integration-tests/src/test/java/com/atlan/java/sdk/PurposeTest.java
Labels: ignore

#1021 Further minor fixes
  buildSrc/src/main/kotlin/com.atlan.kotlin-custom-package.gradle.kts
  integration-tests/src/test/java/com/atlan/java/sdk/AtlanLiveTest.java
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVWriter.kt
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  sdk/src/main/java/com/atlan/cache/AbstractMassCache.java
  sdk/src/main/java/com/atlan/cache/AbstractOffHeapCache.java
  sdk/src/main/java/com/atlan/generators/SearchableAttribute.java
  sdk/src/main/java/com/atlan/util/StringUtils.java
  sdk/src/test/java/com/atlan/util/StringUtilsTest.java
Labels: ignore

#1020 Bump to latest snapshot
  .github/workflows/test.yml
  gradle.properties
  gradle/libs.versions.toml
  integration-tests/src/test/java/com/atlan/java/sdk/AtlanLiveTest.java
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorArchivedTest.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ColumnImporter.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpsertRABTest.kt
Labels: ignore

#1026 Adds username and extra fields to credential response
  sdk/src/main/java/com/atlan/model/admin/CredentialResponse.java
Labels: enhancement

#1027 Drop password field that was added in error, will never be populated
  sdk/src/main/java/com/atlan/model/admin/CredentialResponse.java
Labels: ignore

#1030 Correct typo that caused CategoryCache to be loaded incorrectly
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/SameNameCategoriesTest.kt
  samples/packages/asset-import/src/test/resources/same_name_categories.csv
  sdk/src/main/java/com/atlan/cache/AbstractMassCache.java
Labels: bug

#1033 Avoid page overruns in edge cases where total results is very nearly the limit before query rewriting needs to happen
  gradle/libs.versions.toml
  sdk/src/main/java/com/atlan/model/search/AuditSearchResponse.java
  sdk/src/main/java/com/atlan/model/search/IndexSearchResponse.java
  sdk/src/main/java/com/atlan/model/search/SearchLogResponse.java
Labels: bug

#1036 Fixes bug where a purpose with no tag could cause admin export to fail
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/exports/Policies.kt
Labels: bug

#1037 Bump to latest snapshot
  gradle.properties
Labels: ignore

#1044 Adds full delta calculation logic for RAB and CAB
  gradle/libs.versions.toml
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/ChecksumCache.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/AssetResolver.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/DeltaProcessor.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/FileBasedDelta.kt
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/cube-assets-builder/src/main/kotlin/CubeAssetsBuilderCfg.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/AssetImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/ConnectionImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/CubeImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/DimensionImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/FieldImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/HierarchyImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/Importer.kt
  samples/packages/cube-assets-builder/src/main/resources/package.pkl
  samples/packages/cube-assets-builder/src/test/kotlin/com/atlan/pkg/cab/DeltaTest.kt
  samples/packages/cube-assets-builder/src/test/resources/assets_latest.csv
  samples/packages/relational-assets-builder/src/main/kotlin/RelationalAssetsBuilderCfg.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/AssetImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ColumnImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ConnectionImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/DatabaseImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/MaterializedViewImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/SchemaImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/TableImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ViewImporter.kt
  samples/packages/relational-assets-builder/src/main/resources/package.pkl
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpDeltaRABTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/DeltaTest.kt
  samples/packages/relational-assets-builder/src/test/resources/assets_latest.csv
  sdk/src/main/java/com/atlan/cache/AbstractMassCache.java
  sdk/src/main/java/com/atlan/cache/AbstractOffHeapCache.java
  sdk/src/main/java/com/atlan/cache/OffHeapAssetCache.java
  sdk/src/main/java/com/atlan/cache/OffHeapObjectCache.java
  sdk/src/main/java/com/atlan/exception/ErrorCode.java
  sdk/src/main/java/com/atlan/util/AssetBatch.java
Labels: enhancement, packages

#1043 Fixes bug with automated token exchange on expired API token retries
  samples/packages/cube-assets-builder/src/test/kotlin/com/atlan/pkg/cab/CreateThenUpDeltaCABTest.kt
  sdk/src/main/java/com/atlan/net/AtlanRequest.java
  sdk/src/main/java/com/atlan/net/HttpClient.java
Labels: bug

#1049 FT-770 Added logic to prevent updating of connection name.
  gradle/libs.versions.toml
  samples/packages/enrichment-migrator/src/main/kotlin/EnrichmentMigrator.kt
  samples/packages/enrichment-migrator/src/main/kotlin/Transformer.kt
Labels: bug

#1050 Bump to minor version given significant delta calculation logic changes
  .github/workflows/merge.yml
  gradle.properties
Labels: ignore

#1051 Latest model typedefs
  build.gradle.kts
  gradle/libs.versions.toml
  integration-tests/src/test/java/com/atlan/java/sdk/ModelTest.java
  sdk/src/main/java/com/atlan/model/assets/IModelAttributeAssociation.java
  sdk/src/main/java/com/atlan/model/assets/ModelAttributeAssociation.java
  sdk/src/main/java/com/atlan/model/enums/DataProductStatus.java
  sdk/src/main/resources/templates/ModelAttributeAssociation.ftl
  sdk/src/test/java/com/atlan/model/assets/ModelAttributeAssociationTest.java
Labels: experimental

#1052 Bump to latest snapshot
  gradle.properties
  package-toolkit/config/src/main/resources/Renderers.pkl
Labels: ignore

#1054 Bump to latest snapshot
  gradle.properties
Labels: ignore

#1055 Fixes bug that caused full delta calculation to miss net-new assets
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/FileBasedDelta.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpDeltaRABTest.kt
Labels: bug

#1059 Fixes validations when creating a README
  sdk/src/main/java/com/atlan/exception/ErrorCode.java
  sdk/src/main/java/com/atlan/model/assets/Readme.java
  sdk/src/main/resources/templates/Readme.ftl
Labels: bug

#1060 Migrates bulk streaming of search to use `search_after`
  sdk/src/main/java/com/atlan/model/search/IndexSearchDSL.java
  sdk/src/main/java/com/atlan/model/search/IndexSearchRequest.java
  sdk/src/main/java/com/atlan/model/search/IndexSearchResponse.java
Labels: enhancement

#1061 Adds multi-pass handling of cyclical relationships to asset import package
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/InvalidCyclicalRelationshipsTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/MultiPassCyclicalRelationshipsTest.kt
  samples/packages/asset-import/src/test/resources/invalid-cyclical-relationships.csv
  samples/packages/asset-import/src/test/resources/valid-cyclical-relationships.csv
Labels: enhancement, packages

#1067 Dependency bumps
  gradle/libs.versions.toml
Labels: ignore

#1069 Adds limited ability to configure an SSO provider
  sdk/src/main/java/com/atlan/api/SSOEndpoint.java
  sdk/src/main/java/com/atlan/model/admin/SSOMapping.java
  sdk/src/main/java/com/atlan/model/admin/SSOProviderRequest.java
Labels: experimental

#1070 Simplify usage of default client in integration tests
  integration-tests/src/test/java/com/atlan/java/sdk/ADLSAssetTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/AdminTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/AirflowAssetTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/AtlanLiveTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/AtlanTagTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/AzureEventHubTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/ConnectionTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/CubeTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/CustomMetadataTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/DataMeshTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/GCSAssetTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/GlossaryTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/InsightsTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/KafkaTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/LineageTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/ModelTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/PersonaTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/PresetAssetTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/PurposeTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/QueryParserTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/RequestsTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/S3AssetTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/SQLAssetTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/SSOTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/SearchTest.java
  integration-tests/src/test/java/com/atlan/java/sdk/SupersetAssetTest.java
Labels: ignore
