Repository atlanhq/atlan-java, pull requests merged in 2024-12, with the labels that each got.

#1073 JavaDocs fixes and event toolkit removal
  .github/workflows/merge.yml
  .github/workflows/release.yml
  sdk/src/main/java/com/atlan/model/assets/Asset.java
  sdk/src/main/java/com/atlan/model/assets/AtlanCollection.java
  sdk/src/main/java/com/atlan/model/assets/AuthPolicy.java
  sdk/src/main/java/com/atlan/model/assets/Connection.java
  sdk/src/main/java/com/atlan/model/typedefs/AttributeDefOptions.java
  sdk/src/main/resources/templates/Asset.ftl
  sdk/src/main/resources/templates/AtlanCollection.ftl
  sdk/src/main/resources/templates/AttributeDefOptions.ftl
  sdk/src/main/resources/templates/AuthPolicy.ftl
  sdk/src/main/resources/templates/Connection.ftl
Labels: ignore

#1075 Add eventual consistency loop for integration test
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/MultiPassCyclicalRelationshipsTest.kt
Labels: ignore

#1076 Fix eventual consistency conditions for integration test
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/MultiPassCyclicalRelationshipsTest.kt
Labels: ignore

#1077 Fix eventual consistency conditions for integration test
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/MultiPassCyclicalRelationshipsTest.kt
Labels: ignore

#1079 Remove parallelism for final flush of parallel batches
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/MultiPassCyclicalRelationshipsTest.kt
  sdk/src/main/java/com/atlan/util/ParallelBatch.java
Labels: ignore

#1080 Bound retry loop in integration test
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/MultiPassCyclicalRelationshipsTest.kt
Labels: ignore

#1081 Further concurrency hygiene
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVReader.kt
  sdk/src/main/java/com/atlan/cache/OffHeapAssetCache.java
  sdk/src/main/java/com/atlan/util/ParallelBatch.java
Labels: ignore

#1084 Fix impersonation within packages
  gradle.properties
  gradle/libs.versions.toml
  package-toolkit/config/src/main/resources/Renderers.pkl
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
Labels: bug

#1088 Corrects error messages given removal of default client
  sdk/src/main/java/com/atlan/exception/ErrorCode.java
Labels: ignore

#1089 Bump to latest snapshot
  gradle.properties
Labels: ignore

#1093 Adds default file check to ignore
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
Labels: bug

#1095 Fixes bug that attempted to process non-existent input files
  gradle/libs.versions.toml
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/Importer.kt
  samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/Loader.kt
  samples/packages/openapi-spec-loader/src/main/kotlin/OpenAPISpecLoader.kt
Labels: bug

#1096 Bump to latest snapshot
  .github/release.yml
  gradle.properties
Labels: ignore

#1097 Fixes bug where URL-based ingestion of OpenAPI spec would fail
  samples/packages/openapi-spec-loader/src/main/kotlin/OpenAPISpecLoader.kt
Labels: bug

#1098 Adds logging of underlying causes for back-end errors
  sdk/src/main/java/com/atlan/exception/ErrorCode.java
  sdk/src/main/java/com/atlan/model/core/AtlanError.java
  sdk/src/main/java/com/atlan/net/LiveAtlanResponseGetter.java
Labels: enhancement

#1099 Bump to latest snapshot
  gradle.properties
Labels: ignore

#1105 Dependency bumps
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#1107 Fixes cyclical relationship detection in asset import
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  sdk/src/main/java/com/atlan/net/LiveAtlanResponseGetter.java
Labels: bug

#1108 Corrects credentials for JavaDocs publishing
  sdk/build.gradle.kts
Labels: ignore

#1109 Improves logging on any CSV decoding errors
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/CellXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/ConnectionXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/DataDomainXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/GlossaryCategoryXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/GlossaryTermXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/GlossaryXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/GroupXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/ModelAssetXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/RoleXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/UserXformer.kt
Labels: enhancement, packages

#1110 Fixes persistent connection cache population
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/PersistentConnectionCache.kt
Labels: bug

#1114 Adds OpenTelemetry logging for custom packages
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
  package-toolkit/runtime/src/main/resources/log4j2.xml
Labels: enhancement

#1116 Rollback to previous version of library
  gradle/libs.versions.toml
  sdk/build.gradle.kts
Labels: ignore

#1118 Parallelize package tests
  .github/workflows/test.yml
Labels: ignore

#1119 Parallelize package tests
  .github/workflows/test.yml
Labels: ignore

#1120 Parallelize integration tests
  .github/workflows/test.yml
Labels: ignore

#1121 Isolate outputs for parallel tests
  .github/workflows/test.yml
Labels: ignore

#1122 Optimizations for parallel integration tests
  .github/workflows/test.yml
  integration-tests/build.gradle.kts
Labels: ignore

#1123 Add OpenTelemetry dependencies to jar file
  package-toolkit/runtime/build.gradle.kts
Labels: ignore

#1124 Swap to known-working Gradle command
  .github/workflows/test.yml
Labels: ignore

#1126 Swap around OpenTelemetry initialization
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
Labels: ignore

#1127 Add missing package for otel to log4j config
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
  package-toolkit/runtime/src/main/resources/log4j2.xml
Labels: ignore

#1133 Attempt to auto-configure otel
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
  package-toolkit/runtime/src/main/resources/log4j2.xml
Labels: ignore

#1134 Fix dependencies for otel
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
Labels: ignore

#1135 Force consistent version of otel dependencies
  build.gradle.kts
  buildSrc/src/main/kotlin/com.atlan.kotlin-custom-package.gradle.kts
  buildSrc/src/main/kotlin/com.atlan.kotlin.gradle.kts
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
Labels: ignore

#1137 Inject otel agent into base images
  .github/workflows/merge.yml
  .github/workflows/release.yml
  gradle/libs.versions.toml
Labels: ignore

#1139 Add otel appender to config
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
  package-toolkit/runtime/src/main/resources/log4j2.xml
Labels: ignore

#1140 Bundle dependencies for otel appender in shadow jar
  package-toolkit/runtime/build.gradle.kts
Labels: ignore

#1141 Add log4j base dependencies for pattern parsing
  package-toolkit/runtime/build.gradle.kts
  package-toolkit/runtime/src/main/resources/log4j2.xml
Labels: ignore

#1143 Fix OpenTelemetry for use with log4j2
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
Labels: ignore

#1144 Increase log buffer to capture pre-OTel initialization
  package-toolkit/runtime/src/main/resources/log4j2.xml
  package-toolkit/testing/src/main/resources/log4j2.xml
Labels: ignore

#1148 Migrate from OTel agent back to SDK
  .github/workflows/merge.yml
  .github/workflows/release.yml
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
Labels: ignore

#1150 Move to SDK-aligned OTel instrumentation library
  gradle/libs.versions.toml
Labels: dependencies

#1151 Bump to latest snapshot
  gradle.properties
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/InvalidUsersGroupsTest.kt
Labels: ignore

#1166 Adds dynamic wait based on rate-limit response header
  gradle/libs.versions.toml
  sdk/src/main/java/com/atlan/net/HttpClient.java
Labels: enhancement

#1167 OTel dependency bumps
  gradle/libs.versions.toml
Labels: dependencies

#1169 Remove unused methods and simplify
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
  samples/packages/openapi-spec-loader/src/main/kotlin/OpenAPISpecLoader.kt
Labels: ignore

#1174 Fixes typedef toolkit to generate appropriate AttributeDefs on RelationshipDefs
  gradle/libs.versions.toml
  samples/typedefs/build.gradle.kts
  samples/typedefs/src/main/resources/Custom.pkl
  typedef-toolkit/model/src/main/resources/Model.pkl
Labels: experimental

#1181 Adds interchangeable Excel and CSV options for export packages
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/TabularWriter.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVWriter.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/xls/ExcelSheetWriter.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/xls/ExcelWriter.kt
  samples/packages/admin-export/src/main/kotlin/AdminExportCfg.kt
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/AdminExporter.kt
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/exports/Groups.kt
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/exports/Personas.kt
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/exports/Policies.kt
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/exports/Purposes.kt
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/exports/Users.kt
  samples/packages/admin-export/src/main/resources/package.pkl
  samples/packages/admin-export/src/test/kotlin/ExportAllAdminInfoCSVTest.kt
  samples/packages/admin-export/src/test/kotlin/ExportAllAdminInfoTest.kt
  samples/packages/adoption-export/src/main/kotlin/AdoptionExportCfg.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/AdoptionExporter.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/AssetChanges.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/AssetViews.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/DetailedSearches.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/DetailedUserChanges.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/DetailedUserViews.kt
  samples/packages/adoption-export/src/main/resources/package.pkl
  samples/packages/adoption-export/src/test/kotlin/ExportChangesCSVTest.kt
  samples/packages/metadata-impact-report/src/main/kotlin/MetadataImpactReportCfg.kt
  samples/packages/metadata-impact-report/src/main/kotlin/com/atlan/pkg/mdir/Reporter.kt
  samples/packages/metadata-impact-report/src/main/kotlin/com/atlan/pkg/mdir/metrics/Metric.kt
  samples/packages/metadata-impact-report/src/main/resources/package.pkl
  samples/packages/metadata-impact-report/src/test/kotlin/ImpactReportCSVTest.kt
Labels: packages

#1177 CXD-347 : Support for `Anaplan` typedefs
  integration-tests/src/test/java/com/atlan/java/sdk/AnaplanAssetTest.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanApp.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanDimension.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanLineItem.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanList.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanModel.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanModule.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanPage.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanView.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanWorkspace.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplan.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanApp.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanDimension.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanLineItem.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanList.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanModel.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanModule.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanPage.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanView.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanWorkspace.java
  sdk/src/main/java/com/atlan/model/enums/AtlanConnectorType.java
  sdk/src/main/resources/templates/AnaplanApp.ftl
  sdk/src/main/resources/templates/AnaplanDimension.ftl
  sdk/src/main/resources/templates/AnaplanLineItem.ftl
  sdk/src/main/resources/templates/AnaplanList.ftl
  sdk/src/main/resources/templates/AnaplanModel.ftl
  sdk/src/main/resources/templates/AnaplanModule.ftl
  sdk/src/main/resources/templates/AnaplanPage.ftl
  sdk/src/main/resources/templates/AnaplanView.ftl
  sdk/src/main/resources/templates/AnaplanWorkspace.ftl
  sdk/src/test/java/com/atlan/model/assets/AnaplanAppTest.java
  sdk/src/test/java/com/atlan/model/assets/AnaplanDimensionTest.java
  sdk/src/test/java/com/atlan/model/assets/AnaplanLineItemTest.java
  sdk/src/test/java/com/atlan/model/assets/AnaplanListTest.java
  sdk/src/test/java/com/atlan/model/assets/AnaplanModelTest.java
  sdk/src/test/java/com/atlan/model/assets/AnaplanModuleTest.java
  sdk/src/test/java/com/atlan/model/assets/AnaplanPageTest.java
  sdk/src/test/java/com/atlan/model/assets/AnaplanViewTest.java
  sdk/src/test/java/com/atlan/model/assets/AnaplanWorkspaceTest.java
Labels: enhancement

#1182 FT-864 Change rendering to support Open Telemetry logging
  package-toolkit/config/src/main/resources/Renderers.pkl
Labels: packages
