Repository atlanhq/atlan-java, pull requests merged in 2024-10, with the labels that each got.

#874 Bump to latest snapshot
  gradle.properties
Labels: ignore

#880 Make new version-agnostic attribute Cassandra-cacheable
  samples/typedefs/src/main/resources/DataModel.pkl
Labels: ignore

#881 Adds CVE scanning and detection, fixes transitive versions
  .github/workflows/pr-build.yml
  .github/workflows/test.yml
  build.gradle.kts
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
  package-toolkit/testing/build.gradle.kts
  sdk/build.gradle.kts
Labels: dependencies

#893 Dependency bumps
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#896 Only debug-level log the Atlan SDK
  generate/src/main/resources/log4j2.xml
  gradle.properties
  integration-tests/src/test/resources/log4j2.xml
  package-toolkit/runtime/src/main/resources/log4j2.xml
  package-toolkit/testing/src/main/resources/log4j2.xml
  samples/standalone/sdk-extension/src/main/resources/log4j2.xml
  sdk/src/main/java/com/atlan/net/HttpClient.java
Labels: enhancement

#897 Improve error handling of tests cleanup
  samples/packages/tests-cleanup/src/main/kotlin/TestsCleanup.kt
Labels: ignore

#898 Adds an option to export all attributes
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/RowSerde.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/TimestampXformer.kt
  samples/packages/asset-export-basic/src/main/kotlin/AssetExportBasicCfg.kt
  samples/packages/asset-export-basic/src/main/kotlin/AssetExporter.kt
  samples/packages/asset-export-basic/src/main/kotlin/Exporter.kt
  samples/packages/asset-export-basic/src/main/resources/package.pkl
Labels: packages

#899 Restore main info logging
  generate/src/main/resources/log4j2.xml
  integration-tests/src/test/resources/log4j2.xml
  package-toolkit/runtime/src/main/resources/log4j2.xml
  package-toolkit/testing/src/main/resources/log4j2.xml
  samples/standalone/sdk-extension/src/main/resources/log4j2.xml
Labels: bug

#900 Bump to latest snapshot
  gradle.properties
Labels: ignore

#905 Fixes missing updatedBy property on Credential object
  gradle/libs.versions.toml
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/model/Credential.kt
Labels: bug

#909 Further experimental work on data model assets
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com.atlan.kotlin-custom-package.gradle.kts
  buildSrc/src/main/kotlin/com.atlan.kotlin.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  integration-tests/src/test/java/com/atlan/java/sdk/ModelTest.java
  sdk/src/main/java/com/atlan/model/assets/IModel.java
  sdk/src/main/java/com/atlan/model/assets/ModelAttribute.java
  sdk/src/main/java/com/atlan/model/assets/ModelAttributeAssociation.java
  sdk/src/main/java/com/atlan/model/assets/ModelDataModel.java
  sdk/src/main/java/com/atlan/model/assets/ModelEntity.java
  sdk/src/main/java/com/atlan/model/assets/ModelEntityAssociation.java
  sdk/src/main/java/com/atlan/model/enums/DataModelType.java
  sdk/src/main/java/com/atlan/model/graph/ModelEntityGraph.java
  sdk/src/main/java/com/atlan/model/graph/ModelGraph.java
  sdk/src/main/resources/templates/IModel.ftl
  sdk/src/main/resources/templates/ModelAttribute.ftl
  sdk/src/main/resources/templates/ModelAttributeAssociation.ftl
  sdk/src/main/resources/templates/ModelDataModel.ftl
  sdk/src/main/resources/templates/ModelEntity.ftl
  sdk/src/main/resources/templates/ModelEntityAssociation.ftl
  sdk/src/main/resources/templates/ModelVersion.ftl
  sdk/src/main/resources/templates/entity_interface.ftl
Labels: experimental

#911 Adds detailed search log entry option to adoption export
  samples/packages/adoption-export/src/main/kotlin/AdoptionExportCfg.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/AdoptionExporter.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/AssetChanges.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/DetailedSearches.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/DetailedUserChanges.kt
  samples/packages/adoption-export/src/main/kotlin/com/atlan/pkg/adoption/exports/DetailedUserViews.kt
  samples/packages/adoption-export/src/main/resources/package.pkl
  samples/packages/adoption-export/src/test/kotlin/ExportDetailsTest.kt
  sdk/src/main/java/com/atlan/model/enums/UTMTags.java
  sdk/src/main/java/com/atlan/model/search/AuditSearch.java
  sdk/src/main/java/com/atlan/model/search/IndexSearchRequest.java
  sdk/src/main/java/com/atlan/model/search/SearchLogEntry.java
  sdk/src/main/java/com/atlan/model/search/SearchLogRequest.java
Labels: packages

#912 Bump to latest snapshot
  gradle.properties
Labels: ignore

#914 Bump to latest snapshot
  gradle.properties
Labels: ignore

#921 DVX-703: Added a new `RelationshipDef` for the implementation of an entity by one or more assets
  samples/typedefs/src/main/resources/DataModel.pkl
Labels: enhancement

#922 Use requested connection qualifiedName as fallback
  gradle/libs.versions.toml
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
Labels: bug, packages

#923 CXD-251: Added `INRIVER` connector type
  sdk/src/main/java/com/atlan/model/enums/AtlanConnectorType.java
Labels: enhancement

#927 Adds stronger concurrency controls to parallel batching
  sdk/src/main/java/com/atlan/util/ParallelBatch.java
Labels: enhancement

#938 Fixes a bug where stale connection admins could prevent adding others
  samples/packages/api-token-connection-admin/src/main/kotlin/ApiTokenConnectionAdmin.kt
Labels: bug, packages

#936 Correct GCS -> ADLS for logging
  gradle/libs.versions.toml
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/objectstore/ADLSSync.kt
Labels: bug

#940 Further concurrency tweaks
  sdk/src/main/java/com/atlan/util/AssetBatch.java
  sdk/src/main/java/com/atlan/util/ParallelBatch.java
Labels: enhancement

#944 Changes default load option for relational assets builder back to incremental
  gradle/libs.versions.toml
  samples/packages/relational-assets-builder/src/main/resources/package.pkl
Labels: packages

#946 Bump to latest snapshot
  gradle.properties
Labels: ignore

#960 DVX-739: Added a new attribute `modelEntityAssociationQualifiedName` to the `ModelAttributeAssociation`
  samples/typedefs/src/main/resources/DataModel.pkl
Labels: enhancement

#963 Dependency bumps
  gradle/libs.versions.toml
Labels: dependencies

#964 dvx-736 Add logic to exit from link check when matching link found
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/AssetRefXformer.kt
Labels: ignore

#969 Construct proper user-agent strings
  build.gradle.kts
  gradle/libs.versions.toml
  sdk/src/main/java/com/atlan/net/HttpClient.java
Labels: bug

#970 Bump to latest snapshot
  gradle.properties
Labels: ignore
