Repository atlanhq/atlan-java, pull requests merged in 2025-02, with the labels that each got.

#1280 Ensure artifacts are passed via DAG
  package-toolkit/config/src/main/resources/FrameworkRenderer.pkl
Labels: ignore

#1282 Migrates relational assets builder to new approach
  package-toolkit/config/src/main/resources/Framework.pkl
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  samples/packages/relational-assets-builder/src/main/resources/package.pkl
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpDeltaRABTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CreateThenUpsertRABTest.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/PartialAssetsTest.kt
Labels: packages

#1283 Fixes hand-off of delta parameters for RAB
  package-toolkit/config/src/main/resources/Framework.pkl
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  samples/packages/relational-assets-builder/src/main/resources/package.pkl
Labels: ignore

#1284 Adds stats and error file outputs to asset import
  package-toolkit/config/src/main/resources/Framework.pkl
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVReader.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/ImportResults.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/main/resources/package.pkl
  sdk/src/main/java/com/atlan/cache/OffHeapFailureCache.java
  sdk/src/main/java/com/atlan/util/AssetBatch.java
  sdk/src/main/java/com/atlan/util/ParallelBatch.java
Labels: packages

#1286 Remove case-sensitivity on connectorType, attempt to auto-match other enums
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/EnumXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVReader.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/AssetXformer.kt
  samples/packages/relational-assets-builder/src/test/kotlin/com/atlan/pkg/rab/CaseInsensitiveConnectorTypeTest.kt
  samples/packages/relational-assets-builder/src/test/resources/assets_upper.csv
Labels: bug, packages

#1287 Add asset import support for nested columns
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/CellXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/MapXformer.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/NestedColumnsTest.kt
  samples/packages/asset-import/src/test/resources/nested_columns.csv
Labels: packages

#1288 Dependency bumps
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#1289 Creates a single consolidated results file
  package-toolkit/config/src/main/resources/Framework.pkl
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/DeltaProcessor.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/main/resources/package.pkl
Labels: packages

#1290 Fixes potential NPE when bulk adding to an off-heap cache
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVImporter.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/ImportResults.kt
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/DomainImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/GTCImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/ProductImporter.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/LoadFailureTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/NestedColumnsTest.kt
  samples/packages/asset-import/src/test/resources/assets_invalid.csv
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/AssetImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/Importer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ConnectionImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  sdk/src/main/java/com/atlan/cache/AbstractOffHeapCache.java
  sdk/src/main/java/com/atlan/cache/OffHeapFailureCache.java
  sdk/src/main/java/com/atlan/util/AssetBatch.java
  sdk/src/main/java/com/atlan/util/ParallelBatch.java
Labels: bug

#1293 Bump to latest snapshot
  gradle.properties
  gradle/libs.versions.toml
Labels: ignore

#1294 Adds defensive checks for invalid types in asset import files
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/DomainImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/GTCImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/ProductImporter.kt
Labels: packages

#1295 Fixes a bug in parallelized-deletion during delta processing
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/FileBasedDelta.kt
Labels: bug

#1296 Fixes potential error if there are empty rows in the input CSV
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/DomainImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/GTCImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/ProductImporter.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportDataDomainTest.kt
Labels: ignore

#1300 Bump dependencies
  gradle/libs.versions.toml
Labels: dependencies

#1301 APP-4979 : Anaplan System Dimension
  integration-tests/src/test/java/com/atlan/java/sdk/AnaplanAssetTest.java
  sdk/src/main/java/com/atlan/model/assets/AnaplanSystemDimension.java
  sdk/src/main/java/com/atlan/model/assets/IAnaplanSystemDimension.java
  sdk/src/main/java/com/atlan/model/assets/ICatalog.java
  sdk/src/main/java/com/atlan/model/typedefs/AttributeDefOptions.java
  sdk/src/main/resources/templates/AnaplanSystemDimension.ftl
  sdk/src/test/java/com/atlan/model/assets/AnaplanSystemDimensionTest.java
Labels: experimental

#1307 APP-5136 : Addition of new connectors
  sdk/src/main/java/com/atlan/model/enums/AtlanConnectorType.java
Labels: enhancement

#1308 Adds relational asset builder as a publish target
  gradle/libs.versions.toml
  package-toolkit/config/src/main/resources/Framework.pkl
Labels: packages

#1316 Enhances widgets used in package toolkit
  package-toolkit/config/src/main/resources/Framework.pkl
  samples/packages/api-token-connection-admin/src/main/resources/package.pkl
  samples/packages/openapi-spec-loader/src/main/resources/package.pkl
  samples/packages/tests-cleanup/src/main/kotlin/TestsCleanup.kt
Labels: packages

#1317 Adds errorCause to response payloads
  sdk/src/main/java/com/atlan/model/core/AtlanError.java
Labels: enhancement

#1318 Adds tag management to asset import
  integration-tests/src/test/java/com/atlan/java/sdk/AtlanTagTest.java
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/CellXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVXformer.kt
  samples/packages/asset-import/src/main/kotlin/AssetImportCfg.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AtlanTagImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/main/resources/package.pkl
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/CreateThenUpDeltaAIMTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/DeltaTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/TagManagementTest.kt
  samples/packages/asset-import/src/test/resources/assets.csv
  samples/packages/asset-import/src/test/resources/assets_latest.csv
  samples/packages/asset-import/src/test/resources/tags.csv
  sdk/src/main/java/com/atlan/api/TypeDefsEndpoint.java
  sdk/src/main/java/com/atlan/model/typedefs/AtlanTagDef.java
Labels: packages

#1324 Adds generic SourceTag handling
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AtlanTagImporter.kt
  samples/packages/asset-import/src/test/resources/tags.csv
  sdk/src/main/java/com/atlan/model/assets/DatabricksUnityCatalogTag.java
  sdk/src/main/java/com/atlan/model/assets/DbtTag.java
  sdk/src/main/java/com/atlan/model/assets/SourceTag.java
  sdk/src/main/java/com/atlan/model/structs/AuthPolicyCondition.java
  sdk/src/main/java/com/atlan/model/structs/BusinessPolicyRule.java
  sdk/src/main/java/com/atlan/model/structs/Histogram.java
  sdk/src/main/java/com/atlan/model/structs/SourceTagAttachment.java
  sdk/src/main/java/com/atlan/model/structs/SourceTagAttribute.java
  sdk/src/main/resources/templates/DatabricksUnityCatalogTag.ftl
  sdk/src/main/resources/templates/DbtTag.ftl
  sdk/src/main/resources/templates/SourceTag.ftl
  sdk/src/main/resources/templates/struct.ftl
Labels: ignore

#1325 Dependency bumps
  gradle/libs.versions.toml
Labels: dependencies

#1332 Pin all GitHub Actions to specific versions
  .github/workflows/custom-package-container.yml
  .github/workflows/merge.yml
  .github/workflows/pr-build.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: dependencies

#1339 Corrects integration test to use SourceTag directly
  gradle/libs.versions.toml
  integration-tests/src/test/java/com/atlan/java/sdk/AtlanTagTest.java
  sdk/src/main/java/com/atlan/cache/AbstractAssetCache.java
  sdk/src/main/java/com/atlan/model/assets/SnowflakeTag.java
  sdk/src/main/resources/templates/SnowflakeTag.ftl
Labels: ignore

#1341 Adds logic to detect multi-character field separators and fast-fail
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/main/resources/package.pkl
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/Importer.kt
  samples/packages/cube-assets-builder/src/main/resources/package.pkl
  samples/packages/enrichment-migrator/src/main/kotlin/EnrichmentMigrator.kt
  samples/packages/enrichment-migrator/src/main/resources/package.pkl
  samples/packages/lake-formation-tag-sync/src/main/resources/package.pkl
  samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/Loader.kt
  samples/packages/lineage-builder/src/main/resources/package.pkl
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  samples/packages/relational-assets-builder/src/main/resources/package.pkl
Labels: packages

#1343 Changes default behavior for tag propagation to false
  sdk/src/main/java/com/atlan/api/AssetEndpoint.java
  sdk/src/main/java/com/atlan/model/core/AtlanTag.java
Labels: breaking

#1338 APP-5338 | add new connector types cratedb and kx
  sdk/src/main/java/com/atlan/model/enums/AtlanConnectorType.java
Labels: enhancement

#1344 Fixes missing connector types and improves error handling in lineage builder package
  samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/AssetTransformer.kt
  samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/LineageTransformer.kt
  samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/Loader.kt
  sdk/src/main/java/com/atlan/model/enums/AtlanConnectorType.java
Labels: bug, packages

#1349 APP-5080 Fix CSV exports in admin-export package
  samples/packages/admin-export/src/main/kotlin/AdminExportCfg.kt
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/AdminExporter.kt
  samples/packages/admin-export/src/main/resources/package.pkl
Labels: packages

#1350 Remove erroneous JavaDoc comments
  sdk/src/main/java/com/atlan/model/assets/Asset.java
  sdk/src/main/resources/templates/Asset.ftl
Labels: ignore

#1358 Bump to latest snapshot
  buildSrc/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: ignore

#1359 Fixes null-checking for already-existing workflow configs
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/Utils.kt
  samples/packages/asset-import/src/main/kotlin/AssetImportCfg.kt
Labels: bug

#1360 Bump to latest snapshot
  gradle.properties
Labels: ignore

#1364 Add explicit OTel API dependency
  gradle/libs.versions.toml
  package-toolkit/runtime/build.gradle.kts
  sdk/build.gradle.kts
Labels: ignore

#1366 Adds API tree widget to package toolkit
  package-toolkit/config/src/main/resources/Framework.pkl
Labels: packages

#1380 Dependency bumps
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#1379 Skips attempting to process assigned entities and logs a warning in asset import
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/GTCImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/TermImporter.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/GlossariesWithAssetsTest.kt
  samples/packages/asset-import/src/test/resources/gtc_with_assets.csv
Labels: packages

#1180 FT-728: Add domain <> asset linking to basic export and import
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/FieldSerde.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/RowDeserializer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/CellXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/DataDomainXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/RowPreprocessor.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/DeltaProcessor.kt
  package-toolkit/runtime/src/test/kotlin/serde/ISO8601TimestampsTest.kt
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/asset-export-basic/src/main/kotlin/AssetExporter.kt
  samples/packages/asset-export-basic/src/test/kotlin/ExportDomainRelationshipTest.kt
  samples/packages/asset-export-basic/src/test/resources/domain_relation.csv
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/ImportDomainRelationshipTest.kt
  samples/packages/asset-import/src/test/resources/domain_relationships.csv
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/Importer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
Labels: packages
