Repository atlanhq/atlan-java, pull requests merged in 2025-01, with the labels that each got.

#1183 FT-679 Modified findByType to use regular expression.
  sdk/src/main/java/com/atlan/model/workflow/WorkflowSearchRequest.java
Labels: bug

#1185 Bump to latest snapshot
  gradle.properties
Labels: ignore

#1187 Adds more meaningful error message on invalid enum values
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/CellXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/EnumXformer.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/InvalidEnumTest.kt
  samples/packages/asset-import/src/test/resources/invalid_enum_value.csv
Labels: bug

#1188 Fixes attempts to send empty payloads when no tag is found
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/InvalidTagTest.kt
  samples/packages/asset-import/src/test/resources/invalid_tag.csv
  sdk/src/main/java/com/atlan/model/core/AtlanObject.java
Labels: bug

#1191 Fixes table partition creators and adds latest typedefs
  integration-tests/src/test/java/com/atlan/java/sdk/SQLAssetTest.java
  sdk/src/main/java/com/atlan/model/assets/Column.java
  sdk/src/main/java/com/atlan/model/assets/DataverseAttribute.java
  sdk/src/main/java/com/atlan/model/assets/DataverseEntity.java
  sdk/src/main/java/com/atlan/model/assets/ICatalog.java
  sdk/src/main/java/com/atlan/model/assets/IDataverse.java
  sdk/src/main/java/com/atlan/model/assets/IDataverseAttribute.java
  sdk/src/main/java/com/atlan/model/assets/IDataverseEntity.java
  sdk/src/main/java/com/atlan/model/assets/TablePartition.java
  sdk/src/main/java/com/atlan/model/typedefs/AttributeDefOptions.java
  sdk/src/main/resources/templates/Column.ftl
  sdk/src/main/resources/templates/TablePartition.ftl
  sdk/src/test/java/com/atlan/model/assets/DataverseAttributeTest.java
  sdk/src/test/java/com/atlan/model/assets/DataverseEntityTest.java
Labels: enhancement

#1195 Fixes deadlock on data domain caching
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/cache/DataDomainCache.kt
Labels: bug

#1197 Fixes creation details for multi-valued custom metadata attributes
  integration-tests/src/test/java/com/atlan/java/sdk/CustomMetadataTest.java
  sdk/src/main/java/com/atlan/model/typedefs/AttributeDef.java
Labels: bug

#1198 Optimizes cache refreshing to minimize unnecessary cache thrashing
  gradle.properties
  sdk/src/main/java/com/atlan/cache/AbstractMassCache.java
  sdk/src/main/java/com/atlan/cache/AtlanTagCache.java
  sdk/src/main/java/com/atlan/cache/CustomMetadataCache.java
  sdk/src/main/java/com/atlan/model/search/AuditDetail.java
  sdk/src/main/java/com/atlan/model/search/EntityAudit.java
  sdk/src/main/java/com/atlan/serde/AssetDeserializer.java
  sdk/src/main/java/com/atlan/serde/AtlanTagDeserializer.java
  sdk/src/main/java/com/atlan/serde/AuditDetailDeserializer.java
  sdk/src/main/java/com/atlan/serde/CustomMetadataAuditDeserializer.java
  sdk/src/main/java/com/atlan/serde/EntityAuditDeserializer.java
Labels: enhancement

#1199 Fix null-handling for embedded audit details
  sdk/src/main/java/com/atlan/serde/EntityAuditDeserializer.java
Labels: ignore

#1202 Bump to latest snapshot
  buildSrc/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: ignore

#1206 Fixes case-sensitivity of connector type on import packages
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/AssetResolver.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/AssetImporter.kt
  samples/packages/cube-assets-builder/src/main/kotlin/com/atlan/pkg/cab/Importer.kt
  samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/AssetTransformer.kt
  samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/LineageTransformer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/AssetImporter.kt
Labels: packages

#1212 CXD-379 | Support for Custom typedefs
  integration-tests/src/test/java/com/atlan/java/sdk/CustomAssetTest.java
  package-toolkit/config/src/main/resources/Connectors.pkl
  sdk/src/main/java/com/atlan/model/assets/CustomEntity.java
  sdk/src/main/java/com/atlan/model/assets/ICatalog.java
  sdk/src/main/java/com/atlan/model/assets/ICustom.java
  sdk/src/main/java/com/atlan/model/assets/ICustomEntity.java
  sdk/src/main/java/com/atlan/model/enums/AtlanConnectionCategory.java
  sdk/src/main/java/com/atlan/model/enums/AtlanConnectorType.java
  sdk/src/main/java/com/atlan/model/relations/CustomParentEntityCustomChildEntities.java
  sdk/src/main/java/com/atlan/model/relations/CustomRelatedFromEntitiesCustomRelatedToEntities.java
  sdk/src/main/java/com/atlan/model/typedefs/AttributeDefOptions.java
  sdk/src/main/resources/templates/CustomEntity.ftl
  sdk/src/test/java/com/atlan/model/assets/CustomEntityTest.java
Labels: enhancement

#1213 Dependency bumps
  build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#1215 Dependency bumps
  gradle/libs.versions.toml
Labels: dependencies

#1216 FT-566: Add Non-Technical Group Names Column to the Users sheet
  samples/packages/admin-export/src/main/kotlin/com/atlan/pkg/ae/exports/Users.kt
  samples/packages/admin-export/src/test/kotlin/ExportUsersTest.kt
Labels: packages

#1226 Bump dependencies, including OTel (to be tested)
  gradle/libs.versions.toml
Labels: dependencies

#1227 Downgrade OTel to known-working version
  gradle/libs.versions.toml
Labels: dependencies

#1230 Bump to latest snapshot
  gradle.properties
Labels: ignore

#1231 Fixes potential NPE on clearing attributes
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVImporter.kt
Labels: packages

#1236 Standardize error messages for log parsing
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/ConnectionXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/DataDomainXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/EnumXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/GlossaryCategoryXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/GlossaryTermXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/GlossaryXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/GroupXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/ModelAssetXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/RoleXformer.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/cell/UserXformer.kt
Labels: enhancement

#1250 Provides meaningful error when no data domain supplied for a data product
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/ProductImporter.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/InvalidProductTest.kt
  samples/packages/asset-import/src/test/resources/product_without_domain.csv
Labels: packages

#1252 Fixes maximum token TTE to 5 years
  sdk/src/main/java/com/atlan/api/ApiTokensEndpoint.java
Labels: bug

#1256 Initial work for delta processing in asset import
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/DeltaProcessor.kt
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/util/FileBasedDelta.kt
  samples/packages/asset-import/src/main/kotlin/AssetImportCfg.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/main/resources/package.pkl
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/CreateThenUpDeltaAIMTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/DeltaTest.kt
  samples/packages/asset-import/src/test/kotlin/com/atlan/pkg/aim/MultiConnectionDeltaTest.kt
  samples/packages/asset-import/src/test/resources/assets.csv
  samples/packages/asset-import/src/test/resources/assets_latest.csv
  samples/packages/asset-import/src/test/resources/multi-connection-delta.csv
Labels: packages

#1260 Migrates relational assets builder to asset import delegation
  package-toolkit/runtime/src/main/kotlin/com/atlan/pkg/serde/csv/CSVXformer.kt
  samples/packages/asset-import/src/main/kotlin/AssetImportCfg.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/AssetImporter.kt
  samples/packages/asset-import/src/main/kotlin/com/atlan/pkg/aim/Importer.kt
  samples/packages/asset-import/src/main/resources/package.pkl
  samples/packages/relational-assets-builder/build.gradle.kts
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/AssetXformer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ColumnXformer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ConnectionImporter.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ContainerXformer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/DatabaseXformer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/Importer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/MaterializedViewXformer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/SchemaXformer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/TableXformer.kt
  samples/packages/relational-assets-builder/src/main/kotlin/com/atlan/pkg/rab/ViewXformer.kt
Labels: packages

#1262 APP-4958 Add additional whitespace and missing import to python renderer.
  package-toolkit/config/src/main/resources/Renderers.pkl
Labels: packages

#1239 APP-4737 Enhance MDIR with data domains and products
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/metadata-impact-report/src/main/kotlin/MetadataImpactReportCfg.kt
  samples/packages/metadata-impact-report/src/main/kotlin/com/atlan/pkg/mdir/Reporter.kt
  samples/packages/metadata-impact-report/src/main/kotlin/com/atlan/pkg/mdir/metrics/Metric.kt
  samples/packages/metadata-impact-report/src/main/resources/package.pkl
  samples/packages/metadata-impact-report/src/test/kotlin/ImpactReportCSVTest.kt
  samples/packages/metadata-impact-report/src/test/kotlin/ImpactReportTest.kt
Labels: packages

#1266 Fix unique resolution of pre-existing data products
  samples/packages/metadata-impact-report/src/main/kotlin/com/atlan/pkg/mdir/Reporter.kt
Labels: ignore

#1267 Fixes parallel integration tests with domains and products
  package-toolkit/testing/src/main/kotlin/com/atlan/pkg/PackageTest.kt
  samples/packages/metadata-impact-report/src/test/kotlin/ImpactReportCSVTest.kt
  samples/packages/metadata-impact-report/src/test/kotlin/ImpactReportTest.kt
Labels: ignore

#1268 Change default behavior for saving SDK-run searches to false
  sdk/src/main/java/com/atlan/model/search/IndexSearchRequest.java
Labels: breaking

#1270 Latest model, types and attributes
  sdk/src/main/java/com/atlan/generators/GeneratorConfig.java
  sdk/src/main/java/com/atlan/model/assets/ApplicationField.java
  sdk/src/main/java/com/atlan/model/assets/BusinessPolicy.java
  sdk/src/main/java/com/atlan/model/assets/IApplication.java
  sdk/src/main/java/com/atlan/model/assets/IApplicationField.java
  sdk/src/main/java/com/atlan/model/assets/IBusinessPolicy.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBIColumn.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBIDashboard.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBIDataflow.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBIDataset.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBIMeasure.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBIPage.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBIReport.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBITable.java
  sdk/src/main/java/com/atlan/model/assets/IPowerBITile.java
  sdk/src/main/java/com/atlan/model/assets/ITableauCalculatedField.java
  sdk/src/main/java/com/atlan/model/assets/ITableauDashboard.java
  sdk/src/main/java/com/atlan/model/assets/ITableauDatasource.java
  sdk/src/main/java/com/atlan/model/assets/ITableauDatasourceField.java
  sdk/src/main/java/com/atlan/model/assets/ITableauFlow.java
  sdk/src/main/java/com/atlan/model/assets/ITableauMetric.java
  sdk/src/main/java/com/atlan/model/assets/ITableauWorkbook.java
  sdk/src/main/java/com/atlan/model/assets/ITableauWorksheet.java
  sdk/src/main/java/com/atlan/model/assets/IWorkflow.java
  sdk/src/main/java/com/atlan/model/assets/IWorkflowRun.java
  sdk/src/main/java/com/atlan/model/assets/Workflow.java
  sdk/src/main/java/com/atlan/model/assets/WorkflowRun.java
  sdk/src/main/java/com/atlan/model/structs/AtlanStruct.java
  sdk/src/main/java/com/atlan/model/structs/BusinessPolicyRule.java
  sdk/src/main/java/com/atlan/model/structs/ColumnValueFrequencyMap.java
  sdk/src/main/java/com/atlan/model/structs/Histogram.java
  sdk/src/test/java/com/atlan/model/assets/ApplicationFieldTest.java
  sdk/src/test/java/com/atlan/model/assets/BusinessPolicyTest.java
  sdk/src/test/java/com/atlan/model/assets/WorkflowRunTest.java
  sdk/src/test/java/com/atlan/model/assets/WorkflowTest.java
Labels: enhancement
